image: 192.168.103.210:5000/gitlab-runner:flutter
# стадии сборки
stages:
  - branch-routines
  - build-web
  - build-apk
  - prepare-artifact

include:
  - "/gitlab-ci-templates/rel-pipeline.yml"
  - "/gitlab-ci-templates/linuxbuild-templates.yml"

variables:
  VERSION: " 1.0.0+$CI_PIPELINE_ID"
  VERSION_ARTIFACTS: "1.0.0.$CI_PIPELINE_ID"
  NWT_SERVERS: '{"Тест1": "http://10.160.16.142:8080/"}'
  SOUTH_SERVERS: '{"Long": "http://lz-argusfe.lz.south.rt.ru:8080/"}'
  VOLGA_SERVERS: '{"Тест (dargus)": "http://10.160.16.142:8080/"}'
  URAL_SERVERS: '{"Тест1": "http://10.184.86.35:8080/", "Тест5": "http://10.184.67.30:8080/"}'
