image: 192.168.103.210:5000/gitlab-runner:flutter
# стадии сборки
stages:
  - build-web
  - build-apk
  - build-httpd
  
before_script:
  - chmod 777 ./*
  - dos2unix ./*
  - echo "Get projects dependencies"
  - flutter pub get

# сборка WEB приложения
build web:
  stage: build-web
  script:
    - echo "Build wed application"
    - flutter build web
  tags:
    - light
  artifacts:
    name: $CI_COMMIT_REF_NAME-distrib-artifacts
    expire_in: 7 days
    paths:
      - build/web
    when: always
    
# сборка APK приложения
build apk:
  stage: build-apk
  script:
    - echo "Build apk application"
    - flutter build apk --release
    - echo "Rename build/app/outputs/flutter-apk/app-release.apk to build/app/outputs/flutter-apk/app-release_$CI_PIPELINE_ID.apk"
    - mv ./build/app/outputs/flutter-apk/app-release.apk ./build/app/outputs/flutter-apk/app-release_$CI_PIPELINE_ID.apk
  tags:
    - light
  artifacts:
    name: $CI_COMMIT_REF_NAME-distrib-artifacts
    expire_in: 7 days
    paths:
      - build/app/outputs/flutter-apk/app-release_$CI_PIPELINE_ID.apk
    when: always
    
# сборка HTTPD приложения
build httpd:
  stage: build-httpd
  script:
    - echo "Download httpd-2.4.52-win32-VS16.zip"
    - curl https://www.apachelounge.com/download/VS16/binaries/httpd-2.4.52-win32-VS16.zip --output httpd-2.4.52.zip
    - echo "Unpacking httpd-2.4.52-win32-VS16.zip to ./tmp" 
    - unzip httpd-2.4.52.zip -d ./tmp
    - echo "Coping web to ./tmp/Apache24/htdocs/"
    - cp -r ./web/* ./tmp/Apache24/htdocs/
    - cd ./tmp
    - tar cvfz httpd-2.4-win32-tasklist-lite_$CI_PIPELINE_ID.tar.gz ./*
    - pwd
    - ls -l
  tags:
    - light
  needs: [build web]
  artifacts:
    name: $CI_COMMIT_REF_NAME-distrib-artifacts
    expire_in: 7 days
    paths:
      - build/tmp/httpd-2.4-win32-tasklist-lite_$CI_PIPELINE_ID.tar.gz
    when: always