.filter-rel: &filter-rel
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME =~ /^rel-.*$/

automerge-rel:
  stage: branch-routines
  image: 192.168.103.210:5000/gitlab-runner:2.5
  variables:
    GIT_STRATEGY: none
    SOURCE_BRANCH: "$CI_BUILD_REF_NAME"
    TARGET_BRANCH: ""
  script:
    - pip3 install CMRESHandler
    - python3 "/programmersmount/util/bin/automergegl.py" -b $SOURCE_BRANCH -p $CI_PROJECT_PATH -t "$TARGET_BRANCH" -c "automerge_flutter.conf"
  tags:
    - light
  <<: *filter-rel