name: TaskList Lite build
on:
  push:
    branches:
      - ci-for-tasklist_lite
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v1
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: '11.0.13+8'
          distribution: 'liberica'
      - run: echo "Installed java to the runner."
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build web
      - run: flutter build apk --release
      
      - uses: actions/upload-artifact@v2
        with:
          name: APK for QA
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7

      - name: tar
        run: cd ./build || tar -cvf web.tar ./build/web
      - uses: actions/upload-artifact@v2
        with:
          name: Web
          path: build/web
          retention-days: 7
